---
# handlers file for nginx

- name: enable nginx
  service:
    name: nginx
    enabled: true

- name: start nginx
  service:
    name: nginx
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: stop nginx
  service:
    name: nginx
    state: stopped
